[workspace]
authors = ["bgmeulem"]
description = "A leightweight Python package for calculating and plotting Swarzschild black holes with thin accretion disk."
name = "luminet"
version = "0.1.0"
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

# The Python package `simple_python` uses `hatchling` as Python build backend
[package.host-dependencies]
hatchling = "*"
setuptools = "*"

[package.run-dependencies]
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.2,<3"
scipy = ">=1.15.1,<2"
pandas = ">=2.2.3,<3"
pytest = ">=8.3.4,<9"
toml = ">=0.10.2,<0.11"

[activation]
env = { "PYTHONPATH" = "$PYTHONPATH:$(pwd)/src" }

[environments]
docs = ["docs"]

[tasks]
test = { cmd = "pytest", cwd = "tests"}

[feature.docs.tasks]
build_docs = {cmd = ["make", "html"], description = "Build the documentation", cwd="docs"}
host_docs = {cmd = ["python", "-m", "http.server", "8000"], description = "Host the documentation", cwd="docs/build/html"}

[feature.docs.dependencies]
sphinx = ">=8.1.3,<9"
pygments = ">=2.19.1,<3"
furo = ">=2024.8.6,<2025"
toml = ">=0.10.2,<0.11"
sphinxcontrib-bibtex = ">=2.6.3,<3"
sphinx-copybutton = ">=0.5.2,<0.6"
sphinx-inline-tabs = ">=2023.4.21,<2024"
sphinx-autoapi = ">=3.4.0,<4"

[feature.docs.pypi-dependencies]
catppuccin = { version = ">=2.3.4, <3", extras = ["pygments"] }
sphinx-paramlinks = ">=0.6.0, <0.7"
