name: Luminet Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: prefix-dev/setup-pixi@v0.8.2
      with:
        pixi-version: v0.41.3
        cache: true
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    - name: Test
      run: |
        pixi r test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      if: matrix.os == 'ubuntu-latest'
