# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Luminet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: prefix-dev/setup-pixi@v0.8.0
      with:
        pixi-version: v0.41.3
        cache: true
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    - name: Coverage and test with Codecov and Pytest
      run: |
        pixi r coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
